"""add name column in movie_images table

Revision ID: 33247af2ebfc
Revises: dddbd3505659
Create Date: 2024-08-12 21:50:58.762095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33247af2ebfc'
down_revision = 'dddbd3505659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_images', sa.Column('name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_images', 'name')
    # ### end Alembic commands ###
